apiVersion: v1
kind: Service
metadata:
  name: clickhouse
  namespace: clickhouse
  labels:
    app: clickhouse
  annotations:
spec:
  selector:
    app: clickhouse
  ports:
  - port: 8123
    protocol: TCP
    targetPort: 8123